### PR TITLE
Added Lights Out game info

### PR DESCRIPTION
**Pull request by melissa3000**
For adding tutorials, packages, or apps
===========================================

##### What did you add to the README.md file?
Added the Lights Out game app to the README file

##### Do you want to be added to the contributors list on the README.md file?  

- [ ] Yes
- [x ] No

### CODE REVIEW

**Comment by amrrs** [comment]
@grabear looks like the PR is submitted for master. Please check.

**Review by grabear — CHANGES_REQUESTED** [review]
Please resubmit this PR, but merge to dev-master please.  Otherwise, thanks for the contribution!

**Comment by melissa3000** [comment]
Ok - I changed it to dev-master. Please let me know if I need to change anything else. Thanks!

**Review by grabear — APPROVED** [review]

**Comment by amrrs** [comment]
Thanks!

**Pull request merged**
