### PR TITLE
Add Hadley's book Mastering Shiny

### PR DESCRIPTION
**Pull request by ucg8j**
Because anything Hadley does is awesome!

##### What did you add to the README.md file?
Book - Mastering Shiny, Hadley Wickham

### CODE REVIEW

**Comment by amrrs** [comment]
I tried to review the PR but seems couldn't :P will wait for them to do it!

**Comment by ucg8j** [comment]
@amrrs I think it was because it failed one of the CI bot checks. Which checks if a PR has 'WIP' or 'Work in progress' in the title. I've edited the title. It should now work after you review it - unless you get beaten to it!

**Comment by sdhutchins** [comment]
@amrrs I'll let you handle this one! 😃

**Review by amrrs — APPROVED** [review]
looks good

**Comment by amrrs** [comment]
Thanks @ucg8j  for the PR and Thanks @sdhutchins giving me this ;)

**Pull request merged**
