### PR TITLE
Added Shiny GEM to example apps.

### PR DESCRIPTION
**Pull request by fresh2dev**
For adding tutorials, packages, or apps
===========================================

##### What did you add to the README.md file?

Have you ensured your contribution adheres to the pull request guidelines of [awesome](https://github.com/sindresorhus/awesome/edit/master/pull_request_template.md)? In particular:

- Not a duplicate.
- Only has awesome items. Awesome lists are curations of the best, not everything.
- Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Drop all the `A` / `An` prefixes in the descriptions.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.

----------

##### Do you want to be added to the contributors list on the README.md file?  

- [x] Yes
- [ ] No

##### What name would you like?

Donald Mellenbruch

##### What website would you like your name linked to?
www.donaldmellenbruch.com

### CODE REVIEW

**Review by grabear — CHANGES_REQUESTED** [review]
@dm3ll3n  Please do not add any personal info to the PULL_REQUEST_TEMPLATE.md. 
 THe PR_TEMPLATE.md file simply populates all of the PR description sections with the content of the file. 
 (See your [PR](https://github.com/grabear/awesome-rshiny/pull/63)).  Please revert the PR_Template.md changes.  

Thanks for correcting the typo though!  And for contributing :+1:

**Comment by fresh2dev** [comment]
My mistake; reverted "Filled out PR info."

Thanks!

**Comment by grabear** [comment]
Not a problem!  @dm3ll3n We'll get you on the Contributors list.  Also, please feel free to add anything that we haven't included on our list yet.

**Review by grabear — APPROVED** [review]

**Review by grabear — CHANGES_REQUESTED** [review]
@dm3ll3n Also Merge into the dev-master branch and not the master branch.  Sorry I didn't catch that before.

**Comment by fresh2dev** [comment]
Gotcha. Closing this PR; sent you another. Thanks!

**Pull request closed without merging**
