### PR TITLE
Added tutorials for R-Shiny

### PR DESCRIPTION
**Pull request by benda1997**
For adding tutorials, packages, or apps
===========================================

##### What did you add to the README.md file?

Tutorials for R Shiny

##### Do you want to be added to the contributors list on the README.md file?

Yes

##### What name would you like?

Aditya Bendapudi

##### What website would you like your name linked to?

  Linkedin

### CODE REVIEW

**Comment by grabear** [comment]
@benda1997 Could you please give us the link to your LinkedIn profile.

**Comment by sdhutchins** [comment]
@benda1997 For the tutorials, can you give more descriptive names such as "Neon Data Skills' Rshiny Basics" and for the pdf, who did the pdf?

**Review by sdhutchins — CHANGES_REQUESTED** [review]
For the tutorials, can you give more descriptive names such as "Neon Data Skills' Rshiny Basics" and for the pdf, who did the pdf?

**Comment by benda1997** [comment]
@grabear My Linkedin profile link- https://www.linkedin.com/in/aditya-bendapudi-64147a101

**Review by sdhutchins — APPROVED** [review]

**Comment by sdhutchins** [comment]
@benda1997 thanks for changing the descriptions. For the linkedin link, can you add that to the readme?

**Pull request merged**
