### PR TITLE
add all my contributions to shiny

### PR DESCRIPTION
**Pull request by DivadNojnarg**
For adding tutorials, packages, or apps
===========================================

##### What did you add to the README.md file?
I added all my tutorials:
* [David Granjon](https://divadnojnarg.github.io)
    * [Customize shiny sliderInput](https://divadnojnarg.github.io/blog/customsliderinput/)
    * [Making of: knobInput, a new shiny input](https://divadnojnarg.github.io/blog/knobinput/)
    * [Design beautiful CVs with shiny](https://divadnojnarg.github.io/blog/shinycvs/)
    * [How to extend shinydashboard?](https://divadnojnarg.github.io/blog/awesomedashboards/)
    * [Build Bootstrap 4 dashboards with bs4Dash](https://divadnojnarg.github.io/blog/bs4dash/)
    * [Simple webview for shiny apps](https://divadnojnarg.github.io/blog/shiny_webview/)

I added bs4Dash, argonR, argonDash, shinyEffects and gentelellaShiny packages:
* [bs4Dash](https://github.com/DivadNojnarg/bs4Dash) - Bootstrap 4 version of shinydashboard.
* [argonR](https://github.com/RinteRface/argonR) - R wrapper around the Argon Design System.
* [argonDash](https://github.com/RinteRface/argonDash) - Argon dashboards with R.
* [shinyEffects](https://github.com/DivadNojnarg/shinyEffects) - Fancy CSS effects for shiny.
* [gentelellaShiny](https://github.com/MarkEdmondson1234/gentelellaShiny) - gentella dashboard template for shiny.

I added my name to people:
* [David Granjon](https://github.com/DivadNojnarg)

I updated the book [Web Application and Development Using Shiny (3rd edition) - by Chris Beely](https://www.amazon.com/Application-Development-Using-Shiny-visualizations/dp/1788993128)
to the third edition.

I corrected a typo in the title of the second book: Learning Shiny instead of learing Shiny

I added a lot of shiny apps in the App example section:
* [shinydashboardPlus Gallery]()
  * [shinydashboardPlus demo](http://130.60.24.205/shinydashboardPlus/) - Demo of shinydashboardPlus capabilities.
* [bs4Dash Gallery]()
  * [bs4Dash Classic Showcase](http://130.60.24.205/bs4Dash/showcase/classic/) - A classic showcase for bs4Dash.
  * [bs4Dash Old School Showcase](http://130.60.24.205/bs4Dash/showcase/old_school/) - Old school showcase for bs4Dash.
  * [Metro de Paris](http://130.60.24.205/dreamRs_ratp/) - Explore the "Metro de Paris".
  * [Around the Lorenz Model](http://130.60.24.205/Lorenz_parameters/) - Explore the Lorenz Model.
  * [Lorenz Init](http://130.60.24.205/Lorenz_init/) - Run the Lorenz model with various initial conditions.
  * [Lotka Volterra Models](http://130.60.24.205/Lotka_bdd/) - Explore famous Lotka Volterra models.
* [argonDash Gallery]()
  * [argonDash showcase](http://130.60.24.205/argonDash/) - argonDash showcase.
  * [Gilets Jaunes](http://130.60.24.205/gilets_jaunes/) - App pour suivre le mouvement des gilets jaunes en France.
* [argonR Gallery]()
  * [argonR demo](http://130.60.24.205/example.html) - A static website built with argonR.
* [gentelellaShiny Gallery]()
  * [gentelellaShiny Showcase](http://130.60.24.205/gentelellaDemo/) - Showcase for gentelellaShiny.
  * [shinyLove](http://130.60.24.205/shinyLove/) - App to test your love.
* [shinyCV](https://dgranjon.shinyapps.io/myshinycv/) - A demonstration of the shinyCV package.
* [shinyBulma](https://dgranjon.shinyapps.io/bulmaExtension/) - A demonstration of shinyBulma.

Have you ensured your contribution adheres to the pull request guidelines of [awesome](https://github.com/sindresorhus/awesome/edit/master/pull_request_template.md)? In particular:

Yes

----------

### For first time contributors...

Yes

##### Do you want to be added to the contributors list on the README.md file?  

- [X] Yes
- [ ] No

I spend a significant time checking what is new about Shiny. Therefore, I will be more than happy to contribute to this awesome list!

##### What name would you like?
I added my name in the readme

##### What website would you like your name linked to?
I would like to use this link: https://github.com/DivadNojnarg

### CODE REVIEW

**Review by grabear — COMMENTED** [review]
@DivadNojnarg Normally, I would prefer such large changes to have more granular commits.  Thoughts? @sdhutchins @ucg8j

**Comment by DivadNojnarg** [comment]
@grabear what do you mean exactly by more granular? Do you want more commits with less change by commit?

**Comment by grabear** [comment]
@DivadNojnarg You have one commit for a very large edit.  That's not usually good practice.

**Comment by ucg8j** [comment]
Firstly, welcome it's always great to see a new contributor.

I agree this is bad practice. A large PR requires a large time commitment from the reviewer(s). The aim of the review is to check the edits to the awesome list (e.g. formatting, syntax, working links etc) and for awesomeness of the content itself. The latter is what is particularly time consuming!

I personally don't have time to check all the content on this PR until perhaps the holiday break. If you would like this content added before then, I'd suggest breaking this PR up into at least 7 PRs for the apps, at least 1 for packages and at least 1 per tutorial.

**Comment by DivadNojnarg** [comment]
Sorry for my long silence ... 

I decided to gather all my contributions in only one place: [RinteRface](https://rinterface.com) 
Therefore, I will push it asap, which should considerably simplify this pull request.

**Comment by sdhutchins** [comment]
> Sorry for my long silence ...
> 
> I decided to gather all my contributions in only one place: [RinteRface](https://rinterface.com)
> Therefore, I will push it asap, which should considerably simplify this pull request.

Looking forward to it, @DivadNojnarg!

**Comment by DivadNojnarg** [comment]
For adding tutorials, packages, or apps
===========================================



##### What did you add to the README.md file?


- add the RinteRface project (https://rinterface.com), a collection of HTML templates for Shiny, including shinydashboardPlus
- remove shinydashboardPlus (already included above)
- add my name to the readme

Have you ensured your contribution adheres to the pull request guidelines of [awesome](https://github.com/sindresorhus/awesome/edit/master/pull_request_template.md)? 
yes

----------

### For first time contributors...

##### Do you want to be added to the contributors list on the README.md file?  

- [x ] Yes
- [ ] No

##### What name would you like?

I added my name in the readme

##### What website would you like your name linked to?
Already set up in the readme

**Comment by DivadNojnarg** [comment]
As promised, the reworked PR: I just gathered everything in one relevant place, instead of multiplying items ...

**Comment by sdhutchins** [comment]
Thanks for resubmitting, @DivadNojnarg!

**Review by grabear — APPROVED** [review]
Thank you @DivadNojnarg.  This is a much better PR!

**Pull request merged**
